/*
 *  This file is auto generated by edger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ENCLAVE_T_H
#define EDGER8R_ENCLAVE_T_H

#include "eapp_utils.h"
#include "edge_call.h"
#include "syscall.h"

#include "edger_macros.h"

#include "Enclave_args.h"

EDGE_EXTERNC_BEGIN

/**** OCALL prototypes. ****/
edge_result_t ocall_print_string(
    size_t* _retval,
    const char* str);

edge_result_t ocall_open_file(
    int* _retval,
    const char* name,
    int flags);

edge_result_t ocall_close_file(
    int* _retval,
    int fdesc);

edge_result_t ocall_read_file(
    int* _retval,
    int fdesc,
    char* buf,
    size_t len);

edge_result_t ocall_write_file(
    int* _retval,
    int fdesc,
    const char* name,
    size_t len);

edge_result_t ocall_ree_time(
    int* _retval,
    struct ree_time_t* time);

EDGE_EXTERNC_END

#endif // EDGER8R_ENCLAVE_T_H
