/*
 *  This file is auto generated by edger8r. DO NOT EDIT.
 */
#include "Enclave_t.h"

#include <stdlib.h>
#include <string.h>
#include <wchar.h>

EDGE_EXTERNC_BEGIN

void edge_init(){
  /* Nothing for now, will probably register buffers/callsites
     later */
}

/**** OCALL function wrappers. ****/

edge_result_t ocall_print_string(
    size_t* _retval,
    const char* str)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_print_string_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.str = (char*)str;
    _args.str_len = (str) ? (strlen(str) + 1) : 0;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_print_string_args_t));
    if (str)
        EDGE_ADD_SIZE(_input_buffer_size, _args.str_len * sizeof(char));
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_print_string_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_print_string_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (str)
        EDGE_WRITE_IN_PARAM(str, _args.str_len * sizeof(char), char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_print_string,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_print_string_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

edge_result_t ocall_open_file(
    int* _retval,
    const char* name,
    int flags)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_open_file_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.name = (char*)name;
    _args.name_len = (name) ? (strlen(name) + 1) : 0;
    _args.flags = flags;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_open_file_args_t));
    if (name)
        EDGE_ADD_SIZE(_input_buffer_size, _args.name_len * sizeof(char));
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_open_file_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_open_file_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (name)
        EDGE_WRITE_IN_PARAM(name, _args.name_len * sizeof(char), char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_open_file,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_open_file_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

edge_result_t ocall_close_file(
    int* _retval,
    int fdesc)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_close_file_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.fdesc = fdesc;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_close_file_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_close_file_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_close_file_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_close_file,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_close_file_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

edge_result_t ocall_read_file(
    int* _retval,
    int fdesc,
    char* buf,
    size_t len)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_read_file_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.fdesc = fdesc;
    _args.buf = (char*)buf;
    _args.len = len;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_read_file_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_read_file_args_t));
    if (buf)
        EDGE_ADD_SIZE(_output_buffer_size, _args.len);
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_read_file_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_read_file,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_read_file_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    EDGE_READ_OUT_PARAM(buf, (size_t)(_args.len));

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

edge_result_t ocall_write_file(
    int* _retval,
    int fdesc,
    const char* name,
    size_t len)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_write_file_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.fdesc = fdesc;
    _args.name = (char*)name;
    _args.len = len;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_write_file_args_t));
    if (name)
        EDGE_ADD_SIZE(_input_buffer_size, _args.len);
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_write_file_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_write_file_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    if (name)
        EDGE_WRITE_IN_PARAM(name, _args.len, char*);
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_write_file,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_write_file_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    /* There were no out nor in-out parameters. */

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

edge_result_t ocall_ree_time(
    int* _retval,
    struct ree_time_t* time)
{
    edge_result_t _result = EDGE_FAILURE;

    /* Marshalling struct. */
    ocall_ree_time_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* No pointers to save for deep copy. */

    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.time = (struct ree_time_t*)time;

    /* Compute input buffer size. Include in and in-out parameters. */
    EDGE_ADD_SIZE(_input_buffer_size, sizeof(ocall_ree_time_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    EDGE_ADD_SIZE(_output_buffer_size, sizeof(ocall_ree_time_args_t));
    if (time)
        EDGE_ADD_SIZE(_output_buffer_size, sizeof(struct ree_time_t));
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    EDGE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = EDGE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (ocall_ree_time_args_t*)_input_buffer;
    EDGE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = ocall(
             Enclave_fcn_id_ocall_ree_time,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size)) != EDGE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (ocall_ree_time_args_t*)_output_buffer;
    EDGE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->_retval;
    /* No pointers to restore for deep copy. */
    EDGE_READ_OUT_PARAM(time, (size_t)(sizeof(struct ree_time_t)));

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = EDGE_OK;

done:
    if (_buffer)
        free(_buffer);
    return _result;
}

EDGE_EXTERNC_END
