variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    RPI3_IP_ADDR: 192.168.100.61
    DOCKERHUB_REPO: vc707/test
    CONTAINER_ROOT_DIR: /home/main/ref-ta

before_script:
    - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
    - git submodule update --init --recursive

stages:
    - build
    - test

edger_build:
    variables:
        IMAGE: ${DOCKERHUB_REPO}:ta_keystone_devel
        VOLUME: ${CI_PROJECT_DIR}/ref-ta:${CONTAINER_ROOT_DIR}
        WORKDIR: ${CONTAINER_ROOT_DIR}
    stage: build
    only:
        - master
    tags:
        - shell
    script:
        - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE}
            make keystone_select
        - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE}
            /bin/bash -c "make -C build edger mrproper"

