variables:
    GITLAB_URL: http://150.82.217.189
    GITLAB_USER: vc707
    KEYSTONE_DIR: /home/user/projects/keystone
    KEYSTONE_SDK_DIR: /home/user/projects/keystone/sdk

before_script:

cache:
    untracked: true
    paths:
      - ${KEYSTONE_PATH}

build:
    only:
      - master
    tags:
      - shell

    script:
      - git submodule update --init --recursive
      - export PATH=${PATH}:${KEYSTONE_DIR}/bin
      - make -C keystone
      - make
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf
