variables:
    DOCKER_IMAGE: trasioteam/ta_ref_devel
    DOCKER_IMAGE_OPTEE: trasioteam/optee

.test_template: &test_definition
    variables:
        ENVS: env/dummy.sh
    tags:
        - ref-ta
    only:
        - master
    stage: test
    before_script:
        - git submodule update --init --recursive
        - source ${ENVS}
    after_script:
        - source ${ENVS}
        # cleanup
        - make mrproper

keystone_qemu_default:
    <<: *test_definition
    image: ${DOCKER_IMAGE}:keystone_qemu
    variables:
        ENVS: env/keystone.sh
    script:
        - make build test run

sgx_sim_default:
    <<: *test_definition
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
    script:
        - make build test run

sgx_nuc_default:
    <<: *test_definition
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
    script:
        - MACHINE=NUC make build test run

optee_qemu_default:
    <<: *test_definition
    image: ${DOCKER_IMAGE}:optee_qemu_v8
    variables:
        ENVS: env/optee_qemu.sh
    script:
        - make build test run

optee_rpi3_default:
    <<: *test_definition
    image: ${DOCKER_IMAGE}:optee_rpi3
    variables:
        ENVS: env/optee_rpi3.sh
    script:
        - make build test run

optee_qemu_teep:
    <<: *test_definition
    image: ${DOCKER_IMAGE_OPTEE}:qemu_optee_teep
    variables:
        ENVS: env/optee_qemu_teep.sh
    script:
        - echo "Hi"
        - ls -la
        - cd ~; ls -la; cd ..
        - make build test run
