variables:
#    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
    DOCKER_IMAGE: docker.io/trasioteam/ta_ref_devel
    DOCKER_IMAGE_OPTEE: docker.io/trasioteam/optee

stages:
    - test_mini
    - test_gp
    - test_perf
    - experimental

.test_teep_template: &test_teep_definition
    variables:
        ENVS: env/dummy.sh
    tags:
        - ta-ref
    before_script:
#        - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD} docker.io
        - sed -i '/^https:\/\/gitlab-ci-token/d' ~/.git-credentials || true
        - git config --global http.sslVerify false
        - git config --global credential.helper 'store --file ~/.git-credentials'
        - echo https://gitlab-ci-token:${CI_JOB_TOKEN}@192.168.100.100 >> ~/.git-credentials
        - echo https://gitlab-ci-token:${CI_JOB_TOKEN}@192.168.100.100:443 >> ~/.git-credentials
        - git submodule sync --recursive
        - git submodule update --init --recursive
        - source ${ENVS}
    after_script:
        - source ${ENVS}
        # cleanup
#        - make mrproper

.test_template117: &test_definition117
    variables:
        ENVS: env/dummy.sh
    tags:
        - ta-ref
    before_script:
#        - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD} docker.io
        - sed -i '/^https:\/\/gitlab-ci-token/d' ~/.git-credentials || true
        - git config --global http.sslVerify false
        - git config --global credential.helper 'store --file ~/.git-credentials'
        - echo https://gitlab-ci-token:${CI_JOB_TOKEN}@192.168.100.100 >> ~/.git-credentials
        - echo https://gitlab-ci-token:${CI_JOB_TOKEN}@192.168.100.100:443 >> ~/.git-credentials
        - git submodule sync --recursive
        - git submodule update --init --recursive
        - source ${ENVS}
    after_script:
        - source ${ENVS}
        # cleanup
        - make mrproper


.test_template101: &test_definition101
    variables:
        ENVS: env/dummy.sh
    tags:
        - ref-ta
    before_script:
        - git submodule sync --recursive
        - git submodule update --init --recursive
        - source ${ENVS}
#        - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}
    after_script:
        - source ${ENVS}
        # cleanup
        - make mrproper

keystone_qemu_default:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_qemu
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run TEST_DIR=${TEST_DIR}
keystone_qemu_test_gp:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_qemu
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run TEST_DIR=${TEST_DIR}
keystone_qemu_test_perf:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_qemu
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

keystone_hifive_default:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_hifive
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run MACHINE=HIFIVE TEST_DIR=${TEST_DIR}
keystone_hifive_test_gp:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_hifive
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run MACHINE=HIFIVE TEST_DIR=${TEST_DIR}
keystone_hifive_test_perf:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:keystone_hifive
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run MACHINE=HIFIVE TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

keystone_trvsim_test_gp:
    variables:
        # OVPSIM_LICENCE and MAC_ADDR are defined in CI/CD settings -> Variables.
        SDIMAGE_URL: http://192.168.100.100:2000/keystone_trvsim_hifive_sdimage.tar.xz
        # PORT, OVPSIM_LICENCE, MAC_ADDR are required in .gitlab-ci.yml
        PORT: 10025
        TEST_DIR: test_gp
    tags:
        - shell117
    stage: test_gp
    before_script:
        - wget ${SDIMAGE_URL} -o /dev/null
        - tar xf keystone_trvsim_hifive_sdimage.tar.xz
        - rm -f ~/.ssh/known_hosts
    script:
        # update this repo
        - git submodule update --init --recursive
        - docker-compose -f services/docker-compose.trvsim.yml up --abort-on-container-exit
    after_script:
        # cleanup
        - docker-compose -f services/docker-compose.trvsim.yml down -v

keystone_vc707_default:
    <<: *test_definition117
    # This is tentative, but actually it works!
    image: ${DOCKER_IMAGE}:keystone_qemu
    variables:
        ENVS: env/keystone.sh
        TEST_DIR: test_mini
    stage: test_mini
    only:
        - todo
    script:
        - make build test run MACHINE=VC707 TEST_DIR=${TEST_DIR}

sgx_sim_default:
    # EPYC server seems to get fault. see https://192.168.100.100/rinkai/ta-ref/-/jobs/12748
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run TEST_DIR=${TEST_DIR}
sgx_sim_test_gp:
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run TEST_DIR=${TEST_DIR}
sgx_sim_test_perf:
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

sgx_nuc_default:
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run MACHINE=NUC TEST_DIR=${TEST_DIR}
sgx_nuc_test_gp:
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run MACHINE=NUC TEST_DIR=${TEST_DIR}
sgx_nuc_test_perf:
    <<: *test_definition101
    image: ${DOCKER_IMAGE}:sgx
    variables:
        ENVS: env/sgx_x64.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run MACHINE=NUC TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

optee_qemu_default:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_qemu_v8
    variables:
        ENVS: env/optee_qemu.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run TEST_DIR=${TEST_DIR}
optee_qemu_test_gp:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_qemu_v8
    variables:
        ENVS: env/optee_qemu.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run TEST_DIR=${TEST_DIR}
optee_qemu_test_perf:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_qemu_v8
    variables:
        ENVS: env/optee_qemu.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

optee_rpi3_default:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_rpi3
    variables:
        ENVS: env/optee_rpi3.sh
        TEST_DIR: test_mini
    stage: test_mini
    script:
        - make build test run MACHINE=RPI3 TEST_DIR=${TEST_DIR}
optee_rpi3_test_gp:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_rpi3
    variables:
        ENVS: env/optee_rpi3.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run MACHINE=RPI3 TEST_DIR=${TEST_DIR}
optee_rpi3_test_perf:
    <<: *test_definition117
    image: ${DOCKER_IMAGE}:optee_rpi3
    only:
        # need to rebuild and burn new image
        - todo
    variables:
        ENVS: env/optee_rpi3.sh
        TEST_DIR: test_gp
        PROFILER: "ON"
        DEBUG_TYPE: "RELEASE"
    stage: test_perf
    script:
        - make build test run MACHINE=RPI3 TEST_DIR=${TEST_DIR} PROFILER=${PROFILER} DEBUG_TYPE=${DEBUG_TYPE}

optee_qemu_teep:
    <<: *test_teep_definition
    image: ${DOCKER_IMAGE_OPTEE}:optee_qemu_teep
    variables:
        ENVS: env/optee_qemu_teep.sh
        TEST_DIR: test_gp
    stage: test_gp
    script:
        - make build test run TEST_DIR=${TEST_DIR}

optee_qemu_teep_device:
    <<: *test_teep_definition
    image: ${DOCKER_IMAGE_OPTEE}:optee_qemu_teep
    variables:
        ENVS: env/optee_qemu_teep.sh
        TEST_DIR: test_gp
    stage: experimental
    script:
        - apt-get -y install nodejs; apt-get -y install npm cmake
        - cd ~; pwd; ls -la; cd /builds/rinkai/; ls -la; cd ta-ref/; ls -la; cd teep-device
        - make clean-optee && make build-optee
