variables:
    GITLAB_URL: http://150.82.217.189
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    KEYSTONE_DIR: /home/user/projects/keystone
    KEYSTONE_SDK_DIR: /home/user/projects/keystone/sdk

before_script:

cache:
    untracked: true
    paths:

stages:
    build

build:
    stage: build
    only:
      - master
      - with-build-keystone
    tags:
      - shell

    script:
      - git submodule update --init --recursive
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR}
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf
