variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin

before_script:

cache:
    untracked: true
    paths:

stages:
    - build
    - test

build:
    stage: build
    only:
      - master
    tags:
      - shell

    script:
      - git submodule update --init --recursive
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - rmdir ${KEYSTONE_DIR} || true
      - ./unpack-prebuilt-keystone.sh 2> /dev/null
      - cd ${KEYSTONE_DIR}; ./aist-setup.sh; cd ..
      - ./unpack-prebuilt-optee.sh 2> /dev/null
      - echo pwd=`pwd`
      - cd build-optee; ../unpack-optee-toolchain.sh 2> /dev/null ; cd ..
#      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} keystone
#      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR}
      - make
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf

test:
    stage: test
    only:
      - master
    tags:
      - shell

    script:
      - echo "test"
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - rmdir ${KEYSTONE_DIR} || true
      - ./unpack-prebuilt-keystone.sh 2> /dev/null
#      - git submodule update --init --recursive
#      - cd ${KEYSTONE_DIR}; ./aist-setup.sh; make -j `nproc` image; cd ..
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} keystone
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} check
