variables:
   GITLAB_URL: http://150.82.217.189
   GITLAB_USER: vc707
build:
   only:
     - master
   tags:
     - shell
   script:
     - make
     - make doc
   artifacts:
     paths:
     - tee-internal-doc-draft.pdf
