variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
#    KEYSTONE_DIR: /home/user/projects/keystone
#    KEYSTONE_SDK_DIR: /home/user/projects/keystone/sdk

before_script:

cache:
    untracked: true
    paths:

stages:
    - build
    - test

build:
    stage: build
    only:
      - master
    tags:
      - shell

    script:
      - git submodule update --init --recursive
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} keystone
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR}
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf

test:
    stage: test
    only:
      - master
    tags:
      - shell

    script:
      - echo "test"
      - . env-keystone.sh; make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} check
