variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    RPI3_IP_ADDR: 192.168.100.61
    DOCKERHUB_REPO: vc707/test
    CONTAINER_ROOT_DIR: /home/main/tee-ta-reference

before_script:
    - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}

# cache:
#     untracked: true
#     paths:

stages:
    - build
    - test

intel_sgx_build:
    stage: build
    only:
      - fix_ci
    tags:
      - shell
    script:
      - docker run -v $(pwd):${CONTAINER_ROOT_DIR} -w ${CONTAINER_ROOT_DIR} --rm ${DOCKERHUB_REPO}:ta_sgx_devel make ref-sgx

optee_qemu_build:
    stage: build
    only:
      - fix_ci
    tags:
      - shell
    script:
      - docker run -v $(pwd):${CONTAINER_ROOT_DIR} -w ${CONTAINER_ROOT_DIR} --rm ${DOCKERHUB_REPO}:ta_optee_qemu_devel make ref-optee

keystone_build:
    stage: build
    only:
      - fix_ci
    tags:
      - shell
    script:
      - docker run -v $(pwd):${CONTAINER_ROOT_DIR} -w ${CONTAINER_ROOT_DIR} --rm ${DOCKERHUB_REPO}:ta_keystone_devel make ref-keystone

doc_build:
    stage: build
    before_script:
      - sudo apt-get install -y doxygen
    only:
      - fix_ci
    tags:
      - shell
    script:
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf

test:
    stage: test
    only:
      - fix_ci
    tags:
      - shell
    script:
      - echo "test"
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} keystone
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} check

optee_test:
    stage: test
    only:
      - fix_ci
    tags:
      - shell
    before_script:
      - sudo apt-get install -y expect
    script:
      - mkdir -p ~/.ssh
      - eval "$(ssh-agent -s)"
      # make sure that private key is set on gitlab
      # and public key is appended on ~/.ssh/authorized_keys in the raspberry pi3 board
      - echo "$RPI3_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - ssh-keyscan ${RPI3_IP_ADDR}  >> ~/.ssh/known_hosts
      - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
      - make optee-rpi3-test
