variables:
    GITLAB_URL: http://150.82.217.189
    GITLAB_USER: vc707
    RISC-V_GCC_DIR: /home/user/projects/keystone/riscv/bin
#    KEYSTONE_SDK_DIR: /home/user/projects/keystone/sdk

before_script:

cache:
    untracked: true
    paths:

build:
    only:
      - master
      - with-build-keystone
    tags:
      - shell

    script:
      - git submodule update --init --recursive
      - export PATH=${PATH}:${RISC-V_GCC_DIR}
      - make
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf
