variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    RPI3_IP_ADDR: 192.168.100.61
    DOCKERHUB_REPO: vc707/test
    CONTAINER_ROOT_DIR: /home/main/ref-ta
    WORKDIR: ${CONTAINER_ROOT_DIR}

before_script:
    - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
    - git submodule update --init --recursive
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c ${SCRIPT}

after_script:
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c "make mrproper"

stages:
    - build
    - test

build_edger:
    variables:
        IMAGE: ${DOCKERHUB_REPO}:ta_keystone_devel
        VOLUME: ${CI_PROJECT_DIR}:${CONTAINER_ROOT_DIR}
        SCRIPT: "source env.sh &&
              make keystone_select &&
              make -C build edger"
    stage: build
    only:
        - master
    tags:
        - shell
    script:
        - echo "TODO: check files"

build_depends:
    variables:
        IMAGE: ${DOCKERHUB_REPO}:ta_keystone_devel
        VOLUME: ${CI_PROJECT_DIR}:${CONTAINER_ROOT_DIR}
        SCRIPT: "source env.sh &&
          make keystone_select &&
          make -C build depends"
    stage: build
    only:
        - master
    tags:
        - shell
    script:
        - echo "TODO: check files"
