variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    RPI3_IP_ADDR: 192.168.100.61

before_script:
      - git submodule update --init --recursive
      - . env-keystone.sh
      - yes "" | sudo apt-get install android-tools-adb android-tools-fastboot autoconf \
        automake bc bison build-essential ccache cscope curl device-tree-compiler \
        expect flex ftp-upload gdisk iasl libattr1-dev libc6:i386 libcap-dev \
        libfdt-dev libftdi-dev libglib2.0-dev libhidapi-dev libncurses5-dev \
        libpixman-1-dev libssl-dev libstdc++6:i386 libtool libz1:i386 make \
        mtools netcat python-crypto python3-crypto python-pyelftools \
        python3-pyelftools python-serial python3-serial rsync unzip uuid-dev \
        xdg-utils xterm xz-utils zlib1g-dev || true
      - yes "" | pip3 install pyelftools pycryptodomex || true
      - rmdir ${KEYSTONE_DIR} || true
      - ./unpack-prebuilt-keystone.sh 2> /dev/null
      - cd ${KEYSTONE_DIR}; ./aist-setup.sh; cd ..
      - rm -fr ${OPTEE_DIR} || true
      - ./unpack-prebuilt-optee.sh 2> /dev/null
      - cd build-optee; ../unpack-optee-toolchain.sh 2> /dev/null ; cd ..

cache:
    untracked: true
    paths:

stages:
    - build
    - test

build:
    stage: build
    only:
      - master
    tags:
      - shell

    script:
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - make
      - make doc
    artifacts:
      paths:
        - tee-internal-doc-draft.pdf

test:
    stage: test
    only:
      - master
    tags:
      - shell

    script:
      - echo "test"
      - export PATH=${PATH}:${RISCV_GCC_DIR}
      - . env-keystone.sh
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} keystone
      - make KEYSTONE_DIR=${KEYSTONE_DIR} KEYSTONE_SDK_DIR=${KEYSTONE_SDK_DIR} check

optee_test:
    stage: test
    only:
      # TODO: fix this right before merge
      - optee-rpi3-test
    tags:
      - shell
    # ignore global before_script
    before_script:
      - ''
    script:
      - mkdir -p ~/.ssh
      - eval "$(ssh-agent -s)"
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - ssh-keyscan ${RPI3_IP_ADDR}  >> ~/.ssh/known_hosts
      - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
      - make optee-rpi3-test
