variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RISCV_GCC_DIR: /home/user/projects/keystone/riscv/bin
    RPI3_IP_ADDR: 192.168.100.61
    DOCKERHUB_REPO: vc707/test
    KEYSTONE_IMAGE: vc707/test:ta_ref_keystone_devel
    CONTAINER_ROOT_DIR: /home/main/ref-ta
    WORKDIR: ${CONTAINER_ROOT_DIR}

before_script:
    - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
    - git submodule update --init --recursive
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c "${SCRIPT}"

after_script:
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c "source env.sh && make mrproper"
    - test $(find lib -mindepth 1 | wc -l) -eq 1
    - test $(find include -mindepth 1 | wc -l) -eq 1

stages:
    - build
    - test

keystone:
    variables:
        IMAGE: ${KEYSTONE_IMAGE}
        VOLUME: ${CI_PROJECT_DIR}:${CONTAINER_ROOT_DIR}
        SCRIPT: "source env.sh &&
          make keystone_select &&
          make build"
    stage: build
    only:
        - master
    tags:
        - shell
