variables:
    GITLAB_URL: http://192.168.100.100
    GITLAB_USER: vc707
    RPI3_IP_ADDR: 192.168.100.61
    DOCKERHUB_REPO: vc707/test
    KEYSTONE_IMAGE: vc707/test:ta_ref_keystone_devel
    CONTAINER_ROOT_DIR: /home/main/ref-ta
    WORKDIR: ${CONTAINER_ROOT_DIR}

before_script:
    - docker login -u ${GITLAB_USER} -p ${DOCKERHUB_PASSWD}
    - git submodule update --init --recursive
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c "${SCRIPT}"

after_script:
    - docker run -v ${VOLUME} -w ${WORKDIR} --rm ${IMAGE} /bin/bash -c "export ENABLE_TEE_ENVS=1 && make mrproper"
    # TODO: we want to fail CI if false.
    - test $(find build/lib -mindepth 1 | wc -l) -eq 1
    - test $(find build/include -mindepth 1 | wc -l) -eq 1

stages:
    - build
    - test

keystone:
    variables:
        IMAGE: ${KEYSTONE_IMAGE}
        VOLUME: ${CI_PROJECT_DIR}:${CONTAINER_ROOT_DIR}
        # TODO: this is too nasy, so we use `image:` tag
        SCRIPT: "source keystone.sh &&
          make keystone_select &&
          make build &&
          make test &&
          make run"
    stage: test
    only:
        - master
    tags:
        - shell
    script:
        - 'echo dummy'
