#Use root/example as user/password credentials
version: '3.1'

services:
    trvsim:
        image: trasioteam/riscv_toolchain:trvsim_20200916
        environment:
            SSH_PORT: ${SSH_PORT}
        expose:
            - ${SSH_PORT}
        volumes:
            - ${IMAGE_DIR}:/tmp/image
            - ${OVPSIM_LICENCE_PATH}:/home/trv/Imperas/OVPsim.lic
        mac_address: ${MAC_ADDR}
    test:
        depends_on:
            - trvsim
        image: trasioteam/ta_ref_devel:keystone_trvsim
        volumes:
            - ../:/home/main/ta-ref
        working_dir: /home/main/ta-ref
        stdin_open: true
        tty: true
