version: '3.5'

services:
    tamproto:
        image: trasioteam/tamproto:teep-device-interop
        environment:
            PORT: 8889
        expose:
            - 8889
    builder:
        image: trasioteam/ta_ref_teep_devel:keystone_qemu
        depends_on:
            - tamproto
        volumes:
            - ../:/home/main/ta-ref
        working_dir: /home/main/ta-ref
        entrypoint: >
            /bin/bash -c "
              sleep 5 &&
              curl http://tamproto:8889/api/tam &&
              source env/keystone.sh &&
              make &&
              cd teep-device &&
              make && make &&
              make test TAM_URL=http://tamproto:8889
            "
