version: '3.5'

services:
    tamproto:
        image: trasioteam/tamproto:teep-device-interop
        environment:
            PORT: 8888
        expose:
            - 8888
    trvsim:
        depends_on:
            - tamproto
        image: trasioteam/riscv_toolchain:trvsim_20200731
        environment:
            PORT: ${SSH_PORT}
        ports:
            - ${SSH_PORT}:${SSH_PORT}
        volumes:
            - ${IMAGE_DIR}:/tmp/image
            - ${OVPSIM_LICENCE}:/home/trv/Imperas.20200710/OVPsim.lic
        mac_address: ${MAC_ADDR}
        hostname: ${TRV_HOSTNAME}
    builder:
        image: trasioteam/ta_ref_teep_devel:keystone_trvsim
        depends_on:
            - trvsim
        volumes:
            - ../:/home/main/ta-ref
        working_dir: /home/main/ta-ref
        entrypoint: >
            /bin/bash -c "
              sleep 5 &&
              curl http://tamproto:8888/api/tam &&
              sleep 55 &&
              source env/keystone.sh &&
              make &&
              cd teep-device &&
              make build-keystone-trvsim TRVSIM_PORT=${SSH_PORT} &&
              make test-keystone-trvsim TAM_URL=http://tamproto:8888 TRVSIM_PORT=${SSH_PORT} | tr -d '\r'
            "
