/*
 *  This file is auto generated by edger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ENCLAVE_U_H
#define EDGER8R_ENCLAVE_U_H

#include "edger_macros.h"

#include "Enclave_args.h"

EDGE_EXTERNC_BEGIN

/**** OCALL prototypes. ****/
size_t ocall_print_string(const char* str);

int ocall_open_file(
    const char* name,
    int flags);

int ocall_close_file(int fdesc);

int ocall_read_file(
    int fdesc,
    char* buf,
    size_t len);

int ocall_write_file(
    int fdesc,
    const char* name,
    size_t len);

int ocall_ree_time(struct ree_time_t* time);

EDGE_EXTERNC_END

#endif // EDGER8R_ENCLAVE_U_H
